version: '3.9'

services:
  rawtherapee:
    build:
      context: .
      dockerfile: Dockerfile.${DIST}
      args:
        VERSION_UBUNTU:
        VERSION_ALPINE:
    container_name: rawtherapee
    image: ai2ys/dockerized-rawtherapee/${DIST}:0.0.0
    hostname: rawtherapee
    working_dir: /workspace
    volumes:
      - ${DATA_DIR:-./}:/workspace
